/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)persistence_buildid.h    generated by: makeheader    Thu Feb 28 22:14:36 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef persistence_buildid_h
#define persistence_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "PERSISTENCESERVICE_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* persistence_buildid_h */
