
/* water_publisher.c

A publication of data of type WaterDispenser

This file is derived from code automatically generated by the rtiddsgen 
command:

rtiddsgen -language C -example <arch> water.idl

Example publication of type WaterDispenser automatically generated by 
'rtiddsgen'. To test them follow these steps:

(1) Compile this file and the example subscription.

(2) Start the subscription on the same domain used for RTI Data Distribution
Service with the command
objs/<arch>/water_subscriber <domain_id> <sample_count>

(3) Start the publication on the same domain used for RTI Data Distribution
Service with the command
objs/<arch>/water_publisher <domain_id> <sample_count>

(4) [Optional] Specify the list of discovery initial peers and 
multicast receive addresses via an environment variable or a file 
(in the current working directory) called NDDS_DISCOVERY_PEERS. 

You can run any number of publishers and subscribers programs, and can 
add and remove them dynamically from the domain.

Example:

To run the example application on domain <domain_id>:

On Unix: 

objs/<arch>/water_publisher <domain_id> 
objs/<arch>/water_subscriber <domain_id> 

On Windows:

objs\<arch>\water_publisher <domain_id>  
objs\<arch>\water_subscriber <domain_id>   
*/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "ndds/ndds_c.h"
#include "water.h"
#include "waterSupport.h"

static const char csv_file_name[] = "DDS_Data.csv";

int RTI_SNPRINTF (char *buffer, size_t count, const char *format, ...){
    int length;
    va_list ap;
    va_start(ap, format);
// #ifdef RTI_WIN32
//     length = _vsnprintf_s(buffer, count, count, format, ap);
// #else
    length = vsnprintf(buffer, count, format, ap);
// #endif
     va_end(ap);
     return length;
}


/* Delete all entities */
static int publisher_shutdown(
    DDS_DomainParticipant *participant)
{
    DDS_ReturnCode_t retcode;
    int status = 0;

    if (participant != NULL) {
        retcode = DDS_DomainParticipant_delete_contained_entities(participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_contained_entities error %d\n", retcode);
            status = -1;
        }

        retcode = DDS_DomainParticipantFactory_delete_participant(
            DDS_TheParticipantFactory, participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_participant error %d\n", retcode);
            status = -1;
        }
    }

    /* RTI Data Distribution Service provides finalize_instance() method on
    domain participant factory for people who want to release memory used
    by the participant factory. Uncomment the following block of code for
    clean destruction of the singleton. */
    /*
    retcode = DDS_DomainParticipantFactory_finalize_instance();
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "finalize_instance error %d\n", retcode);
        status = -1;
    }
    */

    return status;
}

int publisher_main(int domainId, int sample_count)
{
    DDS_DomainParticipant *participant = NULL;
    DDS_Publisher *publisher = NULL;
    DDS_Topic *topic = NULL;
    DDS_DataWriter *writer = NULL;
    WaterDispenserDataWriter *WaterDispenser_writer = NULL;
    WaterDispenser *instance = NULL;
    DDS_ReturnCode_t retcode;
    DDS_InstanceHandle_t instance_handle = DDS_HANDLE_NIL;
    const char *type_name = NULL;
    int count = 0;  
    struct DDS_Duration_t send_period = {1,0};

    /* To customize participant QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    participant = DDS_DomainParticipantFactory_create_participant_with_profile(
        DDS_TheParticipantFactory, domainId, "TCP_Library", "TCP_Publisher",
        NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (participant == NULL) {
        printf("create_participant error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* To customize publisher QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    publisher = DDS_DomainParticipant_create_publisher(
        participant, &DDS_PUBLISHER_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (publisher == NULL) {
        fprintf(stderr, "create_publisher error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* Register type before creating topic */
    type_name = WaterDispenserTypeSupport_get_type_name();
    retcode = WaterDispenserTypeSupport_register_type(
        participant, type_name);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "register_type error %d\n", retcode);
        publisher_shutdown(participant);
        return -1;
    }

    /* To customize topic QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    topic = DDS_DomainParticipant_create_topic(
        participant, "Example WaterDispenser",
        type_name, &DDS_TOPIC_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (topic == NULL) {
        fprintf(stderr, "create_topic error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* To customize data writer QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    writer = DDS_Publisher_create_datawriter(
        publisher, topic,
        &DDS_DATAWRITER_QOS_DEFAULT, NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (writer == NULL) {
        fprintf(stderr, "create_datawriter error\n");
        publisher_shutdown(participant);
        return -1;
    }
    WaterDispenser_writer = WaterDispenserDataWriter_narrow(writer);
    if (WaterDispenser_writer == NULL) {
        fprintf(stderr, "DataWriter narrow error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* Create data sample for writing */
    instance = WaterDispenserTypeSupport_create_data_ex(DDS_BOOLEAN_TRUE);
    if (instance == NULL) {
        fprintf(stderr, "WaterDispenserTypeSupport_create_data error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* For a data type that has a key, if the same instance is going to be
    written multiple times, initialize the key here
    and register the keyed instance prior to writing */
    /*
    instance_handle = WaterDispenserDataWriter_register_instance(
        WaterDispenser_writer, instance);
    */
    /* Main loop */
    for (count=0; (sample_count == 0) || (count < sample_count); ++count) {
        FILE* csv_file = fopen(csv_file_name, "r");
        if (csv_file == NULL){
            perror("Unable to open file!\n");
            exit(1);
        }
        else{
            // printf("FOUND %s\n",csv_file_name); // Debugging Logs
        }        

        // Data Type : Referenced from water_subscriber.c:
        // char *UploadTime;
        // bool Hot_Valve;
        // bool Cooling;
        // int Usage_L;
        // bool Warm_Valve;
        // int ColdTemp_Insulation;
        // bool Status;
        // int Usage_MT;
        // int WaterLevel;
        // int ErrorCode;
        // int HotTemp_Insulation;
        // char *Device_ID;
        // bool Refilling;
        // bool SavingPower;
        // long long TimeStamp;
        // bool Heating;
        // bool Cold_Valve;
        // int WarmTemp;
        // int ColdTemp;
        // int Usage_CC;
        // int HotTemp;
        // bool Sterilizing;
        // char *Hardware;
        // char *Mac_Address;
        // int TDS;
        // long long SendTime;

        char line[200];
        int column = 0;
        char *eptr;

        while(fgets(line, sizeof(line), csv_file)){
            char * token;
            token = strtok(line, ",");

            while(token != NULL) {
                // printf("%s %d\n",token,column); // Debugging Logs
                switch(column){
                    case (1):   // (STRING) Value of Upload Time;
                        RTI_SNPRINTF(instance->UploadTime, 32, token);
                        break;
                    case (23):  // (STRING) Value of Device_ID;
                        RTI_SNPRINTF(instance->Device_ID, 32, token);
                        break;
                    case (45):  // (STRING) Value of Hardware;
                        RTI_SNPRINTF(instance->Hardware, 32, token);
                        break;
                    case (47):  // (STRING) Value of Mac_Address;
                        RTI_SNPRINTF(instance->Mac_Address, 32, token);
                        break;
                    case (3):   // (BOOLEAN) Value of Hot_Valve;
                        instance->Hot_Valve = (intptr_t) token - '0';
                        break;
                    case (5):   // (BOOLEAN) Value of Cooling;
                        instance->Cooling = (intptr_t) token - '0';
                        break;
                    case (9):   // (BOOLEAN) Value of Warm_Valve;
                        instance->Warm_Valve = (intptr_t) token - '0';
                        break;
                    case (13):   // (BOOLEAN) Value of Status;
                        instance->Status = (intptr_t) token - '0';
                        break;
                    case (25):   // (BOOLEAN) Value of Refilling;
                        instance->Refilling = (intptr_t) token - '0';
                        break;
                    case (27):   // (BOOLEAN) Value of SavingPower;
                        instance->SavingPower = (intptr_t) token - '0';
                        break;
                    case (31):   // (BOOLEAN) Value of Heating;
                        instance->Heating = (intptr_t) token - '0';
                        break;
                    case (33):   // (BOOLEAN) Value of Cold_Valve;
                        instance->Cold_Valve = (intptr_t) token - '0';
                        break;
                    case (43):   // (BOOLEAN) Value of Sterilizing;
                        instance->Sterilizing = (intptr_t) token - '0';
                        break;
                    case (7):   // (INTEGER) Value of Usage_L;
                        instance->Usage_L = (long) strtol(token, &eptr, 10);
                        break;
                    case (11):   // (INTEGER) Value of ColdTemp_Insulation;
                        instance->ColdTemp_Insulation = (long) strtol(token, &eptr, 10);
                        break;
                    case (15):   // (INTEGER) Value of Usage_MT;
                        instance->Usage_MT = (long) strtol(token, &eptr, 10);
                        break;
                    case (17):   // (INTEGER) Value of WaterLevel;
                        instance->WaterLevel = (long) strtol(token, &eptr, 10);
                        break;
                    case (19):   // (INTEGER) Value of ErrorCode;
                        instance->ErrorCode = (long) strtol(token, &eptr, 10);
                        break;
                    case (21):   // (INTEGER) Value of HotTemp_Insulation;
                        instance->HotTemp_Insulation = (long) strtol(token, &eptr, 10);
                        break;
                    case (35):   // (INTEGER) Value of WarmTemp;
                        instance->WarmTemp = (long) strtol(token, &eptr, 10);
                        break;
                    case (37):   // (INTEGER) Value of ColdTemp;
                        instance->ColdTemp = (long) strtol(token, &eptr, 10);
                        break;
                    case (39):   // (INTEGER) Value of Usage_CC;
                        instance->Usage_CC = (long) strtol(token, &eptr, 10);
                        break;
                    case (41):   // (INTEGER) Value of HotTemp;
                        instance->HotTemp = (long) strtol(token, &eptr, 10);
                        break;
                    case (49):   // (INTEGER) Value of TDS;
                        instance->TDS = (long) strtol(token, &eptr, 10);
                        break;
                    case (29):   // (LONG LONG) Value of TimeStamp;
                        instance->TimeStamp = (long long) strtol(token, &eptr, 10);
                        break;
                    default:
                        break;
                }
                token = strtok(NULL, ",");
                column++;
            }
        }        

        fclose(csv_file);

        /* Modify the data to be written here */
        time_t machine_time;
        struct tm * timeinfo;
        time(&machine_time);
        timeinfo = localtime (&machine_time);
        printf("Publishing, for the %d x - Machine time: %s\n", count, strtok(asctime(timeinfo),"\n" ));

        struct DDS_Time_t current;
        DDS_DomainParticipant_get_current_time(participant, &current); // Official Function
        long long tolong=current.sec;
                         
        // (LONG LONG) Value of SendTime;
        instance-> SendTime=tolong*1000+current.nanosec/1000000;

        /* Write data */
        retcode = WaterDispenserDataWriter_write(
            WaterDispenser_writer, instance, &instance_handle);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "Write Error %d\n", retcode);
        }


        NDDS_Utility_sleep(&send_period);

    }

    /*
    retcode = WaterDispenserDataWriter_unregister_instance(
        WaterDispenser_writer, instance, &instance_handle);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "unregister instance error %d\n", retcode);
    }
    */
    /* Delete data sample */
    retcode = WaterDispenserTypeSupport_delete_data_ex(instance, DDS_BOOLEAN_TRUE);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "WaterDispenserTypeSupport_delete_data error %d\n", retcode);
    }
    /* Cleanup and delete delete all entities */         
    return publisher_shutdown (participant);
}

int main(int argc, char *argv[])
{
    int domain_id = 0;
    int sample_count = 0; /* infinite loop */

    if (argc >= 2) {
        domain_id = atoi(argv[1]);
    }
    if (argc >= 3) {
        sample_count = atoi(argv[2]);
    }

    /* Uncomment this to turn on additional logging
    NDDS_Config_Logger_set_verbosity_by_category(
        NDDS_Config_Logger_get_instance(),
        NDDS_CONFIG_LOG_CATEGORY_API, 
        NDDS_CONFIG_LOG_VERBOSITY_STATUS_ALL);
    */

    return publisher_main(domain_id, sample_count);
}

