/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tcp_version.h    generated by: makeheader    Thu Feb 28 22:14:28 2019
 *
 *		built from:	version.ifc
 */

#ifndef transport_tcp_version_h
#define transport_tcp_version_h

 
#ifndef log_makeheader_h
  #include "log/log_makeheader.h"
#endif
#ifndef transport_tcp_dll_h
  #include "transport_tcp/transport_tcp_dll.h"
#endif
#ifndef dds_c_infrastructure_h 
  #include "dds_c/dds_c_infrastructure.h"
#endif
  
#ifdef __cplusplus
extern "C" {
#endif


typedef struct DDS_ProductVersion_t NDDS_Transport_TCPv4_LibraryVersion;

extern NDDS_Transport_TCP_DllExport
const NDDS_Transport_TCPv4_LibraryVersion *
        NDDS_Transport_TCPv4_get_library_version();

extern NDDS_Transport_TCP_DllExport
const char *NDDS_Transport_TCPv4_get_build_version_string();


#ifdef __cplusplus
}       /* extern "C" */
#endif

#endif /* transport_tcp_version_h */
