/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tcp_buildid.h    generated by: makeheader    Thu Feb 28 22:14:28 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef transport_tcp_buildid_h
#define transport_tcp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTITRANSPORTTCP_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* transport_tcp_buildid_h */
