/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)log_makeheader.h    generated by: makeheader    Thu Feb 28 22:11:16 2019
 *
 *		built from:	makeheader.ifc
 */

#ifndef log_makeheader_h
#define log_makeheader_h



#ifdef __cplusplus
    extern "C" {
#endif


#if defined(RTI_WIN32) || defined(_WIN32)
#pragma warning(disable:4068)
#endif

    #define Public
    #define Package
    #define Peer
	#define RTI_PRIVATE static
#ifndef __cplusplus
/*    #define public
    #define package
    #define peer
    #define private	static
*/
#endif	/* !__cplusplus */


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* log_makeheader_h */
