/*
 * @(#)recordingservice_dll.h    generated by: makeheader    Thu Feb 28 22:15:30 2019
 *
 *		built from:	dll.ifc
 */

#ifndef recordingservice_dll_h
#define recordingservice_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_recordingservice_DLL_EXPORT)
    #define RECORDERDllExport __declspec( dllexport )
  #else
    #define RECORDERDllExport
  #endif /* RTI_recordingservice_DLL_EXPORT */

  #if defined(RTI_recordingservice_DLL_VARIABLE) 
    #if defined(RTI_recordingservice_DLL_EXPORT)
      #define RECORDERDllVariable __declspec( dllexport )
    #else
      #define RECORDERDllVariable __declspec( dllimport )
    #endif /* RTI_recordingservice_DLL_EXPORT */
  #else 
    #define RECORDERDllVariable
  #endif /* RTI_recordingservice_DLL_VARIABLE */
#else
  #define RECORDERDllExport
  #define RECORDERDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */


#endif /* recordingservice_dll_h */
