/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_buildid.h    generated by: makeheader    Thu Feb 28 22:12:48 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef core_version_buildid_h
#define core_version_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCORE_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* core_version_buildid_h */
