/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_boundedSeq.h    generated by: makeheader    Thu Feb 28 22:11:33 2019
 *
 *		built from:	boundedSeq.ifc
 */

#ifndef reda_boundedSeq_h
#define reda_boundedSeq_h


  #ifndef osapi_type_h
    #include "osapi/osapi_type.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


#define REDA_BOUNDED_SEQUENCE(TBoundedSeq, T, TMaxLength) \
    typedef struct { \
        /*e
         * Maximum capacity of sequence.
         */ \
        RTI_UINT32 _maximum;  \
        /*e
         * Actual length of data in sequence.
         */  \
        RTI_UINT32 _length;  \
        /*e
         * Buffer to store the values.
         */  \
        T _buffer[TMaxLength]; \
    } TBoundedSeq;


#ifdef __cplusplus
    }   /* extern "C" */
#endif


#endif /* reda_boundedSeq_h */
