/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_dbShell.h    generated by: makeheader    Thu Feb 28 22:11:33 2019
 *
 *		built from:	dbShell.ifc
 */

#ifndef reda_dbShell_h
#define reda_dbShell_h


  #ifndef reda_database_h
    #include "reda/reda_database.h"
  #endif
  #ifndef reda_worker_h
    #include "reda/reda_worker.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

extern REDADllExport void REDADBShell_run(struct REDADatabase* database,
					  struct REDAWorker* worker);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* reda_dbShell_h */
