/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_requestreply_cpp.h    generated by: makeheader    Thu Feb 28 22:15:37 2019
 *
 *		built from:	requestreply_cpp.ifcxx
 */

#ifndef ndds_requestreply_cpp_h
#define ndds_requestreply_cpp_h


  #include "ndds/ndds_namespace_cpp.h"
  #include "connext_cpp/connext_cpp_requester.h"
  #include "connext_cpp/connext_cpp_replier.h"
  #include "connext_cpp/connext_cpp_simple_replier.h"

#endif /* ndds_requestreply_cpp_h */
