/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)monitor_buildid.h    generated by: makeheader    Thu Feb 28 22:14:11 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef monitor_buildid_h
#define monitor_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIMONITORING_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* monitor_buildid_h */
