/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)monitor_dll.h    generated by: makeheader    Thu Feb 28 22:14:11 2019
 *
 *		built from:	dll.ifc
 */

#ifndef monitor_dll_h
#define monitor_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_monitor_DLL_EXPORT)
    #define RTIMonitorDllExport __declspec( dllexport )
  #else
    #define RTIMonitorDllExport
  #endif /* RTI_monitor_DLL_EXPORT */

  #if defined(RTI_monitor_DLL_VARIABLE) 
    #if defined(RTI_monitor_DLL_EXPORT)
      #define RTIMonitorDllVariable __declspec( dllexport )
    #else
      #define RTIMonitorDllVariable __declspec( dllimport )
    #endif /* RTI_monitor_DLL_EXPORT */
  #else 
    #define RTIMonitorDllVariable
  #endif /* RTI_monitor_DLL_VARIABLE */
#else
  #define RTIMonitorDllExport
  #define RTIMonitorDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */


#endif /* monitor_dll_h */
