/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)monitor_version.h    generated by: makeheader    Thu Feb 28 22:14:11 2019
 *
 *		built from:	version.ifc
 */

#ifndef monitor_version_h
#define monitor_version_h

 
#ifndef log_makeheader_h
  #include "log/log_makeheader.h"
#endif
#ifndef monitor_dll_h
  #include "monitor/monitor_dll.h"
#endif
#ifndef dds_c_infrastructure_h 
  #include "dds_c/dds_c_infrastructure.h"
#endif
  
#ifdef __cplusplus
extern "C" {
#endif


typedef struct DDS_ProductVersion_t RTIMonitor_LibraryVersion;

extern RTIMonitorDllExport
const RTIMonitor_LibraryVersion *RTIMonitor_get_version();

extern RTIMonitorDllExport
const char *RTIMonitor_get_api_build_version_string();


#ifdef __cplusplus
}       /* extern "C" */
#endif

#endif /* monitor_version_h */
