/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_sequence_TNameValuePairSeqSupport.h    generated by: makeheader    Thu Feb 28 22:12:57 2019
 *
 *		built from:	TNameValuePairSeqSupport.c
 */

#ifndef dds_c_sequence_TNameValuePairSeqSupport_h
#define dds_c_sequence_TNameValuePairSeqSupport_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_sequence_TNameValuePairSeqSupport_h */
