/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)cdr_dll.h    generated by: makeheader    Thu Feb 28 22:11:48 2019
 *
 *		built from:	dll.ifc
 */

#ifndef cdr_dll_h
#define cdr_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_cdr_DLL_EXPORT)
    #define RTICdrDllExport __declspec( dllexport )
  #else
    #define RTICdrDllExport
  #endif /* RTI_cdr_DLL_EXPORT */

  #if defined(RTI_cdr_DLL_VARIABLE) 
    #if defined(RTI_cdr_DLL_EXPORT)
      #define RTICdrDllVariable __declspec( dllexport )
    #else
      #define RTICdrDllVariable __declspec( dllimport )
    #endif /* RTI_cdr_DLL_EXPORT */
  #else 
    #define RTICdrDllVariable
  #endif /* RTI_cdr_DLL_VARIABLE */
#else
  #define RTICdrDllExport
  #define RTICdrDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */


#endif /* cdr_dll_h */
