/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)netio_dll.h    generated by: makeheader    Thu Feb 28 22:12:05 2019
 *
 *		built from:	dll.ifc
 */

#ifndef netio_dll_h
#define netio_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_netio_DLL_EXPORT)
    #define RTINetioDllExport __declspec( dllexport )
  #else
    #define RTINetioDllExport
  #endif /* RTI_netio_DLL_EXPORT */

  #if defined(RTI_netio_DLL_VARIABLE) 
    #if defined(RTI_netio_DLL_EXPORT)
      #define RTINetioDllVariable __declspec( dllexport )
    #else
      #define RTINetioDllVariable __declspec( dllimport )
    #endif /* RTI_netio_DLL_EXPORT */
  #else 
    #define RTINetioDllVariable
    #endif /* RTI_netio_DLL_VARIABLE */
#else
  #define RTINetioDllExport
  #define RTINetioDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */

#endif /* netio_dll_h */
