/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)connext_c_buildid.h    generated by: makeheader    Thu Feb 28 22:14:00 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef connext_c_buildid_h
#define connext_c_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "CONNEXTMSGC_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* connext_c_buildid_h */
