/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)connext_c_log.h    generated by: makeheader    Thu Feb 28 22:14:00 2019
 *
 *		built from:	log.ifc
 */

#ifndef connext_c_log_h
#define connext_c_log_h


  #ifndef xqm_c_dll_h
    #include "connext_c/connext_c_dll.h"
  #endif  


#ifndef log_common_h
   #include "log/log_common.h"
#endif


#ifdef __cplusplus
    extern "C" {
#endif


  #define SUBMODULE_XMQ_DUMMY                    (0 << 10)
  #define SUBMODULE_XMQ_REQUESTREPLY             (1 << 10)


  #define XMQ_SUBMODULE_MASK_DUMMY                    (0x0001)


  #define XMQ_SUBMODULE_MASK_REQUESTREPLY             (0x0002)


  #define XMQ_SUBMODULE_MASK_ALL                        (0xFFFFFF)

extern XMQCDllExport void
XMQLog_getBitmaps(RTILogBitmap *submoduleMask,
		  RTILogBitmap *instrumentationMask);

extern XMQCDllExport void
XMQLog_setBitmaps(RTILogBitmap submoduleMask,
		  RTILogBitmap instrumentationMask);

extern XMQCDllExport
void XMQLog_setVerbosity(RTILogBitmap submoduleMask, int verbosity);

extern XMQCDllVariable const struct RTILogMessage XMQ_LOG_REPLIER_SEND_ERROR_d;


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* connext_c_log_h */
