/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_interpreter.h    generated by: makeheader    Thu Feb 28 22:13:03 2019
 *
 *		built from:	interpreter.ifcxx
 */

#ifndef dds_cpp_interpreter_h
#define dds_cpp_interpreter_h


  #ifndef dds_cpp_dll_h
    #include "dds_cpp/dds_cpp_dll.h"
  #endif
  #ifndef dds_c_typecode_h
    #include "dds_c/dds_c_typecode.h"
  #endif
  #ifndef dds_c_interpreter_h
    #include "dds_c/dds_c_interpreter.h"
  #endif

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_short_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_long_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_ushort_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_ulong_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_float_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_double_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_boolean_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_char_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_octet_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_longlong_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_ulonglong_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_longdouble_w_new;

 extern DDSCPPDllVariable DDS_TypeCode DDS_g_tc_wchar_w_new;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_short_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_long_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_ushort_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_ulong_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_float_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_double_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_boolean_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_char_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_octet_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_longlong_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_ulonglong_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_longdouble_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_wchar_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_string_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_wstring_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_std_string_seq;

 extern DDSCPPDllVariable RTIXCdrSampleAccessInfo DDS_g_sai_std_string;

#endif /* dds_cpp_interpreter_h */
