/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_buildid.h    generated by: makeheader    Thu Feb 28 22:13:03 2019
 *
 *		built from:	buildid.ifcxx
 */

#ifndef dds_cpp_buildid_h
#define dds_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCPP_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* dds_cpp_buildid_h */
