/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)routingservice_processor_impl.h    generated by: makeheader    Thu Feb 28 22:15:02 2019
 *
 *		built from:	processor_impl.ifc
 */

#ifndef routingservice_processor_impl_h
#define routingservice_processor_impl_h


  #ifndef router_dll_h
    #include "routingservice/routingservice_dll.h"
  #endif
  #include "routingservice/routingservice_processor.h"
  #ifdef __cplusplus
      extern "C" {
  #endif

extern ROUTERDllExport
struct RTI_RoutingServiceStreamReaderExt *
RTI_RoutingServiceRoute_get_decorated_stream_reader(
        RTI_RoutingServiceRoute * self,
        struct RTI_RoutingServiceStreamReaderExt * streamReader);

extern ROUTERDllExport
struct RTI_RoutingServiceStreamWriterExt *
RTI_RoutingServiceRoute_get_decorated_stream_writer(
        RTI_RoutingServiceRoute * self,
        struct RTI_RoutingServiceStreamWriterExt * streamWriter);

extern ROUTERDllExport
void RTI_RoutingServiceRoute_notify_stream_reader_listener(
        RTI_RoutingServiceRoute * self,
        struct RTI_RoutingServiceStreamReaderExt * streamReader);

extern ROUTERDllExport
struct RTI_RoutingServiceConnectionExt *
RTI_RoutingServiceRoute_get_input_connection(
        RTI_RoutingServiceRoute * self,
        struct RTI_RoutingServiceStreamReaderExt * streamReader);

extern ROUTERDllExport
struct RTI_RoutingServiceConnectionExt *
RTI_RoutingServiceRoute_get_output_connection(
        RTI_RoutingServiceRoute * self,
        struct RTI_RoutingServiceStreamWriterExt * streamWriter);

extern ROUTERDllExport
void RTI_RoutingServiceRoute_set_stream_port_user_data(
        RTI_RoutingServiceRoute * self,
        void *streamPort,
        void *userData);

extern ROUTERDllExport
void * RTI_RoutingServiceRoute_get_stream_port_user_data(
        RTI_RoutingServiceRoute * self,
        void *streamPort);


  #ifdef __cplusplus
    }	/* extern "C" */
  #endif

#endif /* routingservice_processor_impl_h */
