/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_version.h    generated by: makeheader    Thu Feb 28 22:13:15 2019
 *
 *		built from:	version.ifc
 */

#ifndef metp_version_h
#define metp_version_h

 
#ifndef log_makeheader_h
  #include "log/log_makeheader.h"
#endif
#ifndef metp_dll_h
  #include "metp/metp_dll.h"
#endif
#ifndef dds_c_infrastructure_h 
  #include "dds_c/dds_c_infrastructure.h"
#endif
  
#ifdef __cplusplus
  extern "C" {
#endif


typedef struct DDS_ProductVersion_t METP_LibraryVersion;

extern METPDllExport
const METP_LibraryVersion *METP_get_library_version();

extern METPDllExport
const char *METP_get_build_version_string();


#ifdef __cplusplus
}       /* extern "C" */
#endif


#endif /* metp_version_h */
