/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_dds.h    generated by: makeheader    Thu Feb 28 22:13:14 2019
 *
 *		built from:	dds.ifc
 */

#ifndef metp_dds_h
#define metp_dds_h


#ifndef metp_dll_h
#include "metp/metp_dll.h"
#endif

#include "ndds/ndds_c.h"

#ifdef __cplusplus
extern "C" {
#endif
    

extern METPDllExport DDS_ReturnCode_t
DDS_DataWriter_create_metp_data(
        DDS_DataWriter *self, void **sample, DDS_Boolean *initialize_data);

extern METPDllExport DDS_ReturnCode_t
DDS_DataWriter_delete_metp_data(DDS_DataWriter *self,void *sample);

extern METPDllExport DDS_Boolean
DDS_DataWriter_is_metp_writer(DDS_DataWriter *self);

extern METPDllExport DDS_ReturnCode_t
DDS_DataWriter_write_metp_data(
        DDS_DataWriter *self,
        const void *instance_data,
        const DDS_InstanceHandle_t *handle,
        struct DDS_WriteParams_t *w_params);

extern METPDllExport DDS_ReturnCode_t
DDS_DataReader_is_metp_data_consistent(
        DDS_DataReader *self,
        DDS_Boolean *is_consistent,
        const void *sample,
        const struct DDS_SampleInfo *sample_info);


#ifdef __cplusplus
}       /* extern "C" */
#endif


#endif /* metp_dds_h */
