/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_dll.h    generated by: makeheader    Thu Feb 28 22:13:14 2019
 *
 *		built from:	dll.ifc
 */

#ifndef metp_dll_h
#define metp_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_metp_DLL_EXPORT)
    #define METPDllExport __declspec( dllexport )
  #else
    #define METPDllExport
  #endif /* RTI_metp_DLL_EXPORT */

  #if defined(RTI_metp_DLL_VARIABLE) 
    #if defined(RTI_metp_DLL_EXPORT)
      #define METPDllVariable __declspec( dllexport )
    #else
      #define METPDllVariable __declspec( dllimport )
    #endif /* RTI_metp_DLL_EXPORT */
  #else 
    #define METPDllVariable
  #endif /* RTI_metp_DLL_VARIABLE */
#else
  #define METPDllExport
  #define METPDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */


#endif /* metp_dll_h */
