/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_buildid.h    generated by: makeheader    Thu Feb 28 22:13:15 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef metp_buildid_h
#define metp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "METPC_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* metp_buildid_h */
