/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dl_driver_dll.h    generated by: makeheader    Thu Feb 28 22:11:27 2019
 *
 *		built from:	dll.ifc
 */

#ifndef dl_driver_dll_h
#define dl_driver_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_dl_driver_DLL_EXPORT)
    #define DLDRIVERDllExport __declspec( dllexport )
  #else
    #define DLDRIVERDllExport
  #endif /* RTI_persistence_DLL_EXPORT */

  #if defined(RTI_dl_driver_DLL_VARIABLE) 
    #if defined(RTI_dl_driver_DLL_EXPORT)
      #define DLDRIVERDllVariable __declspec( dllexport )
    #else
      #define DLDRIVERDllVariable __declspec( dllimport )
    #endif /* RTI_persistence_DLL_EXPORT */
  #else 
    #define DLDRIVERDllVariable
  #endif /* RTI_persistence_DLL_VARIABLE */
#else
  #define DLDRIVERDllExport
  #define DLDRIVERDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */


#endif /* dl_driver_dll_h */
