/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataWriter.h    generated by: makeheader    Thu Feb 28 22:13:04 2019
 *
 *		built from:	TDataWriter.cxx
 */

#ifndef dds_cpp_data_TDataWriter_h
#define dds_cpp_data_TDataWriter_h

#endif /* dds_cpp_data_TDataWriter_h */
