/* (c) Copyright 2003-2018, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rti_dl_buildid_cpp.h    generated by: makeheader    Thu Feb 28 22:13:59 2019
 *
 *		built from:	buildid_cpp.ifc
 */

#ifndef rti_dl_buildid_cpp_h
#define rti_dl_buildid_cpp_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIDISTRIBUTEDLOGCPP_BUILD_6.0.0.0_20190301T054126Z_RTI_REL"
#endif

#endif /* rti_dl_buildid_cpp_h */
